# ------------------------------
# Core types
# ------------------------------
type GanttTask {
  TaskID: Int!
  TaskName: String!
  StartDate: String
  EndDate: String
  Duration: Int
  Progress: Int
  ParentId: Int
  Predecessor: String
  Segments: [SegmentsInfo]
  ResourceInfos: [ResourceInfo]
}
input GanttTaskInput {
  TaskID: Int!
  TaskName: String!
  StartDate: String
  EndDate: String
  Duration: Int
  Progress: Int
  ParentId: Int
  Predecessor: String
  Segments: [SegmentsInfoInput]
  ResourceInfos: [ResourceInfoInput]
}

type SegmentsInfo{
  StartDate: String
  EndDate: String
  Duration: Int
}
type ResourceInfo{
  resourceId: Int!
  resourceName: String
  resourceGroup: String
  resourceUnit: Int
}

input SegmentsInfoInput {
  StartDate: String
  EndDate: String
  Duration: Int
}

input ResourceInfoInput {
  resourceId: Int!
  resourceName: String
  resourceGroup: String
  resourceUnit: Int
}

# READ return
type GanttReturnType {
  result: [GanttTask!]!
  count: Int!
}

type Query {
  getTasks: GanttReturnType!
  task(id: Int!): GanttTask
}

type Mutation {
  addTask(value: GanttTaskInput!): GanttTask!
  updateTask(value: GanttTaskInput!): GanttTask!
  deleteTask(key: ID!): Boolean!
}